Allowing custom storage file path
Alymosul/exponent-server-sdk-php pull request #33
Opened 2019-04-13 08:16 UTC by cvele

PR allows for setting a custom token storage files. Very useful in scenarios where vendor dir is not writable.

Instead of using `Expo::normalSetup()` one would get an instance via
```php
$driver = new ExpoFileDriver();
$driver->setStorage('/my/custom/storage/path.json');
$expo = new Expo(new ExpoRegistrar($driver));
```

2019-04-13 13:39 UTC, Alymosul requested changes

2019-04-13 13:39 UTC, Alymosul commented on lib/Repositories/ExpoFileDriver.php
> +        $this->storage = $storage;
$path instead of $storage

2019-04-13 15:26 UTC, cvele commented on lib/Repositories/ExpoFileDriver.php
> +        $this->storage = $storage;
Thanks, sorted

2019-04-14 10:10 UTC, Alymosul commented
Thanks for your contribution! I'll release this feature soon in the coming version :)

2019-04-14 10:10 UTC, Alymosul approved these changes

2019-04-14 10:11 UTC, merged